name: Rubygem Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        type: choice
        description: "Version bump type"
        required: true
        default: "patch"
        options:
          - "major"
          - "minor"
          - "patch"
      release_type:
        type: choice
        description: "Release type"
        required: true
        default: "normal"
        options:
          - "normal"
          - "beta"
          - "alpha"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need all the commits
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: actions/setup-node@v2
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Bump Version
        run: |
          yarn add standard-version
          if [ "${{ github.event.inputs.release_type }}" != "normal" ]; then
            yarn run standard-version --release-as ${{ github.event.inputs.bump_type }} --prerelease ${{ github.event.inputs.release_type }}
          else
            yarn run standard-version --release-as ${{ github.event.inputs.bump_type }}
          fi
      - name: Install deps
        run: |
          bundle install
      - name: publish gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEM_API_KEY}}"
      - name: push changes
        run: |
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
